### ISSUE TITLE
Access to expired posts in PMP

### ISSUE THREAD

**Issue by jarrigoni** [publicmediaplatform/pmpdocs#11]
We can still find posts with the valid dates in the past when searching the PMP. Shouldn't they be removed if the valid dates are in the past?

**Comment by scottsmith130** [comment]
Only the publishers of the documents and users with write permissions can remove old documents/posts in PMP.  PMP itself does not delete old documents/posts. 

There is a query string parameter that can be used to ensure you get only "valid" documents however: `valid=true`
